services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    env_file: .env
    ports: # Добавить публикацию портов
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./www:/var/www/html
      - caddy_data:/data
      - caddy_config:/config
      - /var/log/caddy:/var/log/caddy
    networks:
      - marzban-network
    depends_on:
      marzban:
        condition: service_started

  marzban:
    image: gozargah/marzban:latest
    container_name: marzban
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    env_file: .env
    environment:
      SQLALCHEMY_DATABASE_URL: mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql/${MYSQL_DATABASE}
    volumes:
      - /var/lib/marzban:/var/lib/marzban
      - /var/lib/marzban/certs:/var/lib/marzban/certs
      - /var/lib/marzban/logs:/var/lib/marzban/logs
      - ./marzban/main.patched.py:/code/main.py # тут костыль, по умолчанию dashboard слушает только 127.0.0.1, но у нас всё за Caddy...
    expose: # Оставить expose для внутренней сети
      - "8000"
      - "1080"
      - "8443"
      - "2096"
      - "10000-10100"
    networks:
      - marzban-network

  mysql:
    image: mysql:8.4.0
    container_name: mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    volumes:
      - /var/lib/marzban/mysql:/var/lib/mysql
    networks:
      - marzban-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

volumes:
  marzban_code:
  caddy_data:
  caddy_config:

networks:
  marzban-network:
    driver: bridge