services:
  marzban:
    image: gozargah/marzban:latest
    restart: unless-stopped
    env_file: .env
    expose:
      - "8000"
      - "1080"
      - "8443"
      - "2096"
      - "10000-10100"
    volumes:
      - ./marzban/main.py.patched:/code/main.py          # Патч main.py
      - /var/lib/marzban:/var/lib/marzban                # Данные
      - /var/log/marzban:/var/log/marzban                # Логи
      # Убрал сомнительные монтирования:
      # - ./www:/www
      # - ./marzban/logging.py:/app/logging.py
    networks:
      - internal
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8000/dashboard"]
      interval: 10s
      timeout: 5s
      retries: 5

  caddy:
    image: caddy:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
      - "1080:1080"
      - "8443:8443"
      - "2096:2096"
      - "10000-10100:10000-10100"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./www:/var/www/html                              # файлы статичного сайта - заглушки
      - caddy_data:/data
      - caddy_config:/config
      - /var/log/caddy:/var/log/caddy
    networks:
      - internal
    depends_on:
      marzban:
        condition: service_healthy

volumes:
  caddy_data:
  caddy_config:

networks:
  internal:
    driver: bridge