services:
  marzban:
    image: gozargah/marzban:latest
    restart: unless-stopped
    env_file: .env
    expose:
      - "8000"
      - "1080"
      - "8443"
      - "2096"
      - "10000-10100"
    volumes:
      - marzban_code:/code/
      - /var/lib/marzban:/var/lib/marzban
      - ./marzban/main.patched.py:/code/main.py            # Патч main.py
    networks:
      - internal

  caddy:
    image: caddy:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
      - "1080:1080"
      - "8443:8443"
      - "2096:2096"
      - "10000-10100:10000-10100"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./www:/var/www/html                              # файлы статичного сайта - заглушки
      - caddy_data:/data
      - caddy_config:/config
      - /var/log/caddy:/var/log/caddy
    networks:
      - internal
    depends_on:
      marzban:
        condition: service_started  # Ждём только запуска

volumes:
  marzban_code:
  caddy_data:
  caddy_config:

networks:
  internal:
    driver: bridge